/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPannelHotrogiaodienchinh;

import static View.GiaoDienChinh.GiaoDienChinh.jPanelLamViec;
import Control.KetNoiCSDLMuonSach;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.MuonSachCode;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.MessageFormat;
import javax.swing.JColorChooser;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class MuonsachJPanel extends javax.swing.JPanel {

    private ArrayList<MuonSachCode> list;
    private final DefaultTableModel model;

    public MuonsachJPanel() throws ClassNotFoundException, SQLException {
        initComponents();
        model = (DefaultTableModel) jTableMuonSach.getModel();
        list = new KetNoiCSDLMuonSach().LayThongTin();
        System.out.printf("" + list.size());
        for (int i = 0; i < list.size(); i++) {
            MuonSachCode x = list.get(i);
            model.addRow(new Object[]{
                x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayMuon(), x.getTenSinhVien(), x.getMaTheSinhVien()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldSoPhieuMuon = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMaTheSinhVien = new javax.swing.JTextField();
        jTextFieldTenSinhVien = new javax.swing.JTextField();
        jTextFieldNgayMuon = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jTextFieldMaSoSach = new javax.swing.JTextField();
        jTextFieldTenSach = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButtonThem = new javax.swing.JButton();
        jButtonTaiLai = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonin = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMuonSach = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButtonTimTheoMaTheSinhVien = new javax.swing.JRadioButton();
        jRadioButtonTimTheoSoPhieuMuon = new javax.swing.JRadioButton();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonDoiMau = new javax.swing.JButton();
        jButtonnenTrang = new javax.swing.JButton();
        jButtonnenden = new javax.swing.JButton();
        jLabelnen = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DANH MỤC MƯỢN SÁCH");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 530, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 630, 20));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Thông Tin Mượn Sách");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tên Sách ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ngày Mượn ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Số Lượng");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Số Phiếu Mượn");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mã thẻ Sinh Viên");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tên Sinh Viên");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Mã Số Sách");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextFieldSoPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldSoPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Xử Lí ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Thêm ");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Lưu");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Sửa");
        jButton5.setActionCommand("Sửa ");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jButton6.setBackground(new java.awt.Color(153, 153, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("In");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, -1));

        jButton7.setBackground(new java.awt.Color(153, 153, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Thoát");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 160));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Xử Lí ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Thêm ");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton8.setBackground(new java.awt.Color(153, 153, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Lưu");
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton9.setBackground(new java.awt.Color(153, 153, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Sửa");
        jButton9.setActionCommand("Sửa ");
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jButton10.setBackground(new java.awt.Color(153, 153, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Xóa");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jButton11.setBackground(new java.awt.Color(153, 153, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("In");
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, -1));

        jButton12.setBackground(new java.awt.Color(153, 153, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Thoát");
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 160));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Xử Lí ");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton13.setBackground(new java.awt.Color(153, 153, 0));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("Thêm ");
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton14.setBackground(new java.awt.Color(153, 153, 0));
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("Lưu");
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton15.setBackground(new java.awt.Color(153, 153, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("Sửa");
        jButton15.setActionCommand("Sửa ");
        jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jButton16.setBackground(new java.awt.Color(153, 153, 0));
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("Xóa");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jButton17.setBackground(new java.awt.Color(153, 153, 0));
        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setText("In");
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, -1));

        jButton18.setBackground(new java.awt.Color(153, 153, 0));
        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("Thoát");
        jPanel5.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 160));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 340, 160));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 340, 160));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 340, 160));

        jTextFieldMaTheSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldMaTheSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 30));

        jTextFieldTenSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldTenSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        jTextFieldNgayMuon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldNgayMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        jTextFieldSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, 30));

        jTextFieldMaSoSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldMaSoSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 30));

        jTextFieldTenSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jTextFieldTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, 360));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Xử Lí ");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonThem.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\add.png")); // NOI18N
        jButtonThem.setText("Thêm ");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jButtonTaiLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTaiLai.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\repair.png")); // NOI18N
        jButtonTaiLai.setText("Tải Lại");
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonTaiLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, 30));

        jButtonSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSua.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSua.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\tralai-book.png")); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setActionCommand("Sửa ");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        jButtonXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonXoa.setForeground(new java.awt.Color(0, 0, 0));
        jButtonXoa.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\delete.png")); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 90, -1));

        jButtonin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonin.setForeground(new java.awt.Color(0, 0, 0));
        jButtonin.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\in.png")); // NOI18N
        jButtonin.setText("In");
        jButtonin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, 30));

        jButtonThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThoat.setForeground(new java.awt.Color(0, 0, 0));
        jButtonThoat.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\exit.png")); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 100, -1));
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 140));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 340, 140));

        jTableMuonSach.setBackground(new java.awt.Color(153, 153, 153));
        jTableMuonSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Phiếu Mượn", "Tên Sách", "Mã Số Sách", "Số Lượng", "Ngày Mượn", "Tên Sinh Viên", "Mã Thẻ Sinh Viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMuonSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMuonSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMuonSach.setShowGrid(true);
        jTableMuonSach.getTableHeader().setReorderingAllowed(false);
        jTableMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMuonSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMuonSach);
        if (jTableMuonSach.getColumnModel().getColumnCount() > 0) {
            jTableMuonSach.getColumnModel().getColumn(0).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(1).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(2).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(3).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(4).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(5).setResizable(false);
            jTableMuonSach.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 810, 520));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(153, 153, 153));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Tìm Kiếm Thông Tin");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 200, -1));

        jRadioButtonTimTheoMaTheSinhVien.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButtonTimTheoMaTheSinhVien);
        jRadioButtonTimTheoMaTheSinhVien.setText("Tìm Theo Mã Thẻ Sinh Viên");
        jRadioButtonTimTheoMaTheSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTimTheoMaTheSinhVienActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButtonTimTheoMaTheSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, -1));

        jRadioButtonTimTheoSoPhieuMuon.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButtonTimTheoSoPhieuMuon);
        jRadioButtonTimTheoSoPhieuMuon.setText("Tìm Theo Số Phiếu Mượn");
        jRadioButtonTimTheoSoPhieuMuon.setToolTipText("");
        jRadioButtonTimTheoSoPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTimTheoSoPhieuMuonActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButtonTimTheoSoPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel7.add(jTextFieldTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 30));

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTimKiem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\timkiem.png")); // NOI18N
        jButtonTimKiem.setText("Tìm Kiếm ");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 450, 100));

        jLabel24.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\images.jfif")); // NOI18N
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 280, 170));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDoiMau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDoiMau.setText("Đổi Màu");
        jButtonDoiMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiMauActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonDoiMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        jButtonnenTrang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonnenTrang.setText("Nền Trắng");
        jButtonnenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnenTrangActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonnenTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 30));

        jButtonnenden.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonnenden.setText("Nền Đen");
        jButtonnenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnendenActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonnenden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 30));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 90));

        jLabelnen.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\den.jpg")); // NOI18N
        add(jLabelnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn chắc chắc là mình muốn xóa ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            int index = jTableMuonSach.getSelectedRow();
            int SoPhieuMuon = Integer.parseInt(model.getValueAt(index, 0) + "");
            try {
                if (new KetNoiCSDLMuonSach().Xoa(SoPhieuMuon)) {
                    JOptionPane.showMessageDialog(this, " Xóa Thành Công ");
                    model.removeRow(index);
                    TaiLai();       
    }//GEN-LAST:event_jButtonXoaActionPerformed
            } catch (Exception ex) {
                Logger.getLogger(MuonsachJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Xóa Không Thành Công ");
        }
    }
    private void jRadioButtonTimTheoMaTheSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTimTheoMaTheSinhVienActionPerformed

    }//GEN-LAST:event_jRadioButtonTimTheoMaTheSinhVienActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        
        
        
        
        if(jTextFieldSoPhieuMuon.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Số Phiếu mượn không được bỏ trống ");
            return;
        }    
        try {
            Integer.parseInt(jTextFieldSoPhieuMuon.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
            return ;
        }
        
        boolean kiemtra = false ;
        for(int i = 0; i<list.size() ; i++){
            MuonSachCode muonsach = list.get(i);
            if(muonsach.getSoPhieuMuon() == Integer.parseInt(jTextFieldSoPhieuMuon.getText())){
                kiemtra = true;
            }
        }
        if(kiemtra){
            JOptionPane.showMessageDialog(this,"Số phiếu mượn đã tồn tại");
            return;
        }
        
        
        if(jTextFieldTenSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sách không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSach.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sách là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaSoSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã số sách không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldMaSoSach.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
            return ;
        }    
         
        
        if(jTextFieldSoLuong.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số lượng bắt buộc là chữ số");
            return ;
        }
        
        
        if(jTextFieldNgayMuon.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ngày mượn không được để trống");
            return;
        }
        String ngaymuon = "[0-9]{2}/[0-9]{2}/[0-9]{4}" ;
        if(!jTextFieldNgayMuon.getText().matches(ngaymuon)){
            JOptionPane.showMessageDialog(this,"Ngày mượn bạn nhập không đúng cú pháp");
            return;
        }
        
        
        if(jTextFieldTenSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaTheSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã Thẻ sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldMaTheSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Mã thẻ sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        MuonSachCode x = new MuonSachCode();
        x.setSoPhieuMuon(Integer.parseInt(jTextFieldSoPhieuMuon.getText()));
        x.setTenSach(jTextFieldTenSach.getText());
        x.setMaSoSach(Integer.parseInt(jTextFieldMaSoSach.getText()));
        x.setSoLuong(Integer.parseInt(jTextFieldSoLuong.getText()));
        x.setNgayMuon(jTextFieldNgayMuon.getText());
        x.setTenSinhVien(jTextFieldTenSinhVien.getText());
        x.setMaTheSinhVien(jTextFieldMaTheSinhVien.getText());
        try {
            if (new KetNoiCSDLMuonSach().Them(x)) {
                JOptionPane.showMessageDialog(this, "Thêm Thành Công ");
                model.addRow(new Object[]{
                    x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayMuon(), x.getTenSinhVien(), x.getMaTheSinhVien()
                });
                TaiLai();
            }
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtoninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninActionPerformed
        MessageFormat header = new MessageFormat("Mượn Sách");
        MessageFormat footer = new MessageFormat("");
        try {
            this.jTableMuonSach.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to print");
        }
    }//GEN-LAST:event_jButtoninActionPerformed

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        try {
            TaiLai();
            jButtonThem.setEnabled(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MuonsachJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonTaiLaiActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        GiaoDienChinhJPanel x = new GiaoDienChinhJPanel();
        x.setBounds(0, 0, 1200, 749);
        jPanelLamViec.removeAll();
        jPanelLamViec.add(x);
        jPanelLamViec.validate();
        jPanelLamViec.repaint();


    }//GEN-LAST:event_jButtonThoatActionPerformed

    void TaiLai() throws ClassNotFoundException, SQLException {
        jButtonThem.setEnabled(false);
        jTextFieldSoPhieuMuon.setText("");
        jTextFieldTenSach.setText("");
        jTextFieldMaSoSach.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldNgayMuon.setText("");
        jTextFieldTenSinhVien.setText("");
        jTextFieldMaTheSinhVien.setText("");
        jTableMuonSach.clearSelection();
    }
    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
    
//        if(jTextFieldSoPhieuMuon.getText().equals("")){
//            JOptionPane.showMessageDialog(this,"Số Phiếu mượn không được bỏ trống ");
//            return;
//        }    
//        try {
//            Integer.parseInt(jTextFieldSoPhieuMuon.getText());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
//            return ;
//        }
//        
//        boolean kiemtra = false ;
//        for(int i = 0; i<list.size() ; i++){
//            MuonSachCode muonsach = list.get(i);
//            if(muonsach.getSoPhieuMuon() == Integer.parseInt(jTextFieldSoPhieuMuon.getText())){
//                kiemtra = true;
//            }
//        }
//        if(kiemtra){
//            JOptionPane.showMessageDialog(this,"Số phiếu mượn đã tồn tại");
//            return;
//        }
        
        
        if(jTextFieldTenSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sách không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSach.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sách là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaSoSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã số sách không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldMaSoSach.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Mã số sách bắt buộc là chữ số");
            return ;
        }    
         
        
        if(jTextFieldSoLuong.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số lượng bắt buộc là chữ số");
            return ;
        }
        
        String ngaymuon = "[0-9]{2}/[0-9]{2}/[0-9]{4}" ;
        if(!jTextFieldNgayMuon.getText().matches(ngaymuon)){
            JOptionPane.showMessageDialog(this,"Ngày mượn bạn nhập không đúng cú pháp!!");
            return;
        }
        if(jTextFieldNgayMuon.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ngày mượn không được để trống");
            return;
        }
        
        if(jTextFieldTenSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaTheSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã Thẻ sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldMaTheSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Mã thẻ sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        int index = jTableMuonSach.getSelectedRow();
        MuonSachCode x = new MuonSachCode();
        x.setSoPhieuMuon(Integer.parseInt(jTextFieldSoPhieuMuon.getText()));
        x.setTenSach(jTextFieldTenSach.getText());
        x.setMaSoSach(Integer.parseInt(jTextFieldMaSoSach.getText()));
        x.setSoLuong(Integer.parseInt(jTextFieldSoLuong.getText()));
        x.setNgayMuon(jTextFieldNgayMuon.getText());
        x.setTenSinhVien(jTextFieldTenSinhVien.getText());
        x.setMaTheSinhVien(jTextFieldMaTheSinhVien.getText());

        try {
            if (new KetNoiCSDLMuonSach().Sua(x)) {
                JOptionPane.showMessageDialog(this, " Sửa Thành Công ");
                model.setValueAt(x.getSoPhieuMuon(), index, 0);
                model.setValueAt(x.getTenSach(), index, 1);
                model.setValueAt(x.getMaSoSach(), index, 2);
                model.setValueAt(x.getSoLuong(), index, 3);
                model.setValueAt(x.getNgayMuon(), index, 4);
                model.setValueAt(x.getTenSinhVien(), index, 5);
                model.setValueAt(x.getMaTheSinhVien(), index, 6);
                TaiLai();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Có phải bạn muốn tìm kiếm thông tin ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
        String ma = " ";
        if (jRadioButtonTimTheoMaTheSinhVien.isSelected()) {
            ma = "MaTheSinhVien";
        }
        if (jRadioButtonTimTheoSoPhieuMuon.isSelected()) {
            ma = "SoPhieuMuon";
        }
        String tim = jTextFieldTimKiem.getText();
        try {
            list.clear();
            list = new KetNoiCSDLMuonSach().TimKiemThongTin(ma, tim);
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            for (int i = 0; i < list.size(); i++) {
                MuonSachCode x = list.get(i);
                JOptionPane.showMessageDialog(this,"Tìm kiếm thông tin thành công ");
                model.addRow(new Object[]{
                    x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayMuon(), x.getTenSinhVien(), x.getMaTheSinhVien()
                });
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MuonsachJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jButtonTimKiemActionPerformed
    }else{
            JOptionPane.showMessageDialog(this, "Tìm kiếm thông tin không thành công ");
        }
    }
    private void jRadioButtonTimTheoSoPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTimTheoSoPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTimTheoSoPhieuMuonActionPerformed

    private void jTableMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMuonSachMouseClicked
        jButtonThem.setEnabled(false);
        int index = jTableMuonSach.getSelectedRow();
        jTextFieldSoPhieuMuon.setText(model.getValueAt(index, 0) + "");
        jTextFieldTenSach.setText(model.getValueAt(index, 1) + "");
        jTextFieldMaSoSach.setText(model.getValueAt(index, 2) + "");
        jTextFieldSoLuong.setText(model.getValueAt(index, 3) + "");
        jTextFieldNgayMuon.setText(model.getValueAt(index, 4) + "");
        jTextFieldTenSinhVien.setText(model.getValueAt(index, 5) + "");
        jTextFieldMaTheSinhVien.setText(model.getValueAt(index, 6) + "");

    }//GEN-LAST:event_jTableMuonSachMouseClicked

    private void jButtonDoiMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiMauActionPerformed
        Color color = JColorChooser.showDialog(this, "Chọn màu", Color.yellow);
        jTableMuonSach.setForeground(color);
        jPanel3.setForeground(color);
        jLabel1.setForeground(color);
        jLabel10.setForeground(color);
        jLabelnen.setForeground(color);
        jLabel12.setForeground(color);
        jLabel13.setForeground(color);
        jLabel14.setForeground(color);
        jLabel15.setForeground(color);
        jLabel16.setForeground(color);
        jLabel17.setForeground(color);
        jLabel22.setForeground(color);
        jLabel5.setForeground(color);
        jLabel9.setForeground(color);
        jLabel7.setForeground(color);
        jLabel4.setForeground(color);
        jLabel18.setForeground(color);
        
        jLabel8.setForeground(color);
        jRadioButtonTimTheoMaTheSinhVien.setForeground(color);
        jRadioButtonTimTheoSoPhieuMuon.setForeground(color);
        //        jRadioButtonMa.setForeground(color);
        //        jRadioButtonTen.setForeground(color);
        jButtonin.setForeground(color);
        jButtonSua.setForeground(color);
        jButtonThem.setForeground(color);
        jButtonTaiLai.setForeground(color);
        jButtonTimKiem.setForeground(color);
        jButtonXoa.setForeground(color);
        jButtonThoat.setForeground(color);
        jButtonDoiMau.setForeground(color);
        jButtonnenden.setForeground(color);
        jButtonnenTrang.setForeground(color);
    }//GEN-LAST:event_jButtonDoiMauActionPerformed

    private void jButtonnenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnenTrangActionPerformed
        jLabelnen.setVisible(false);
    }//GEN-LAST:event_jButtonnenTrangActionPerformed

    private void jButtonnendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnendenActionPerformed
        jLabelnen.setVisible(true);
    }//GEN-LAST:event_jButtonnendenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDoiMau;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonin;
    private javax.swing.JButton jButtonnenTrang;
    private javax.swing.JButton jButtonnenden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelnen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonTimTheoMaTheSinhVien;
    private javax.swing.JRadioButton jRadioButtonTimTheoSoPhieuMuon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableMuonSach;
    private javax.swing.JTextField jTextFieldMaSoSach;
    private javax.swing.JTextField jTextFieldMaTheSinhVien;
    private javax.swing.JTextField jTextFieldNgayMuon;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldSoPhieuMuon;
    private javax.swing.JTextField jTextFieldTenSach;
    private javax.swing.JTextField jTextFieldTenSinhVien;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables

    private Object KetNoiCSDLMuonSach() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
