/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPannelHotrogiaodienchinh;

import Control.KetNoiCSDLSach;
import Control.KetNoiCSDLTheDocGia;
import Model.SachCode;
import Model.TheDocGiaCode;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class ThongKeJPanel extends javax.swing.JPanel {

    public ThongKeJPanel() {
        initComponents();
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setToolTipText("");
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonNXB = new javax.swing.JRadioButton();
        jRadioButtonSach = new javax.swing.JRadioButton();
        jRadioButtonDocGia = new javax.swing.JRadioButton();
        jRadioButtonTheLoai = new javax.swing.JRadioButton();
        jRadioButtonMuonHet = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButtonDoiMau = new javax.swing.JButton();
        jButtonnenTrang = new javax.swing.JButton();
        jButtonnenden = new javax.swing.JButton();
        jLabelnen = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thống Kê Số Liệu");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 410, 70));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButtonNXB);
        jRadioButtonNXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonNXB.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonNXB.setText("Thống kê theo NXB");
        jRadioButtonNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNXBActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        buttonGroup1.add(jRadioButtonSach);
        jRadioButtonSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonSach.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonSach.setText("Thống Kê theo sách");
        jRadioButtonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSachActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, -1));

        buttonGroup1.add(jRadioButtonDocGia);
        jRadioButtonDocGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonDocGia.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonDocGia.setText("Thống kê theo độc giả");
        jRadioButtonDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocGiaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonDocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        buttonGroup1.add(jRadioButtonTheLoai);
        jRadioButtonTheLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonTheLoai.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonTheLoai.setText("Thống kê Theo Thể Loại");
        jRadioButtonTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTheLoaiActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        buttonGroup1.add(jRadioButtonMuonHet);
        jRadioButtonMuonHet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonMuonHet.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonMuonHet.setText("Thống kê Sách đã mượn hết");
        jRadioButtonMuonHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMuonHetActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonMuonHet, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 110));

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1160, 510));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Thống Kê ");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Thống Kê ");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Thống Kê ");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Thống Kê ");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhThongKeSoLieu\\thongke.png")); // NOI18N
        jButton7.setText("Thống Kê ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhThongKeSoLieu\\report.png")); // NOI18N
        jButton2.setText("Báo cáo ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 280, 110));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDoiMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDoiMau.setText("Đổi Màu");
        jButtonDoiMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiMauActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonDoiMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jButtonnenTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenTrang.setText("Nền Trắng");
        jButtonnenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnenTrangActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 110, 30));

        jButtonnenden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenden.setText("Nền Đen");
        jButtonnenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnendenActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 30));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 50));

        jLabelnen.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\den.jpg")); // NOI18N
        add(jLabelnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocGiaActionPerformed
        jTable1.removeAll();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã thẻ", "Tên Độc Giả", "Giới tính", "Ngày Sinh", "Địa Chỉ", "Điện Thoại", "Ngày Đăng Kí", "Ngày Hết Hạn"
                }
        ));
        try {
            ArrayList<TheDocGiaCode> list = new KetNoiCSDLTheDocGia().LayThongTin();
            // DefaultTableModel model = (DefaultTableModel) jTable1.getModel();// model.getModel();
            DefaultTableModel MODEL = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < list.size(); i++) {
                TheDocGiaCode x = list.get(i);
                MODEL.addRow(new Object[]{
                    x.getMaThe(), x.getTenDocGia(), x.getGioiTinh(), x.getNgaySinh(), x.getDiaChi(), x.getDienThoai(), x.getNgaytao(), x.getNgayHetHan()
                });
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jRadioButtonDocGiaActionPerformed

    private void jRadioButtonTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTheLoaiActionPerformed

        jTable1.removeAll();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Thể Loại Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản"
                }
        ));
        try {
            ArrayList<SachCode> list = new KetNoiCSDLSach().LayThongTin();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < list.size(); i++) {
                SachCode x = list.get(i);
                model.addRow(new Object[]{
                    x.getTheLoaiSach(), x.getTensach(), x.getTacGia(), x.getNhaXuatBan()
                });
            }
        } catch (Exception ex) {
        }


    }//GEN-LAST:event_jRadioButtonTheLoaiActionPerformed

    private void jRadioButtonMuonHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMuonHetActionPerformed
        jTable1.removeAll();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Số Lượng", "Mã Sách", "Tên Sách"
                }
        ));
        try {
            ArrayList<SachCode> list = new KetNoiCSDLSach().LayThongTinSachDaMuonHet();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < list.size(); i++) {
                SachCode x = list.get(i);
                model.addRow(new Object[]{
                    x.getSoLuong(), x.getMasach(), x.getTensach()
                });
            }
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_jRadioButtonMuonHetActionPerformed

    private void jRadioButtonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSachActionPerformed
        jTable1.removeAll();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Sách", "Tên Sách", "Thể Loại Sách", "Tác Giả", "Số Lượng", "Tình Trạng", "Nhà Xuất Bản", "Năm XB", "Tóm Tắt"
                }
        ));
        try {
            ArrayList<SachCode> list = new KetNoiCSDLSach().LayThongTin();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < list.size(); i++) {
                SachCode x = list.get(i);
                model.addRow(new Object[]{
                    x.getMasach(), x.getTensach(), x.getTheLoaiSach(), x.getTacGia(), x.getSoLuong(), x.getTinhTrang(),
                    x.getNhaXuatBan(), x.getNamXB(), x.getTomTatNoiDung()
                });
            }
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_jRadioButtonSachActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header = new MessageFormat("Thông tin sách");
        MessageFormat footer = new MessageFormat("");
        try {
            this.jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to print");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNXBActionPerformed
        jTable1.removeAll();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nhà Xuất Bản", "Mã Sách", "Tên Sách", "Thể Loại Sách", "Tác Giả", "Năm XB", "Tóm Tắt"
                }
        ));
        try {
            ArrayList<SachCode> list = new KetNoiCSDLSach().LayThongTin();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < list.size(); i++) {
                SachCode x = list.get(i);
                model.addRow(new Object[]{
                    x.getNhaXuatBan(), x.getMasach(), x.getTensach(), x.getTheLoaiSach(), x.getTacGia(), x.getNamXB(), x.getTomTatNoiDung()
                });
            }
        } catch (ClassNotFoundException ex) {
        }

    }//GEN-LAST:event_jRadioButtonNXBActionPerformed

    private void jButtonDoiMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiMauActionPerformed
        Color color = JColorChooser.showDialog(this, "Chọn màu", Color.yellow);

        jTable1.setForeground(color);
        jLabel1.setForeground(color);
        jRadioButtonDocGia.setForeground(color);
        jRadioButtonNXB.setForeground(color);
        jRadioButtonMuonHet.setForeground(color);
        jRadioButtonSach.setForeground(color);
        jRadioButtonTheLoai.setForeground(color);

        //        jRadioButtonMa.setForeground(color);
        //        jRadioButtonTen.setForeground(color);
        jButton2.setForeground(color);
        jButton3.setForeground(color);
        jButton4.setForeground(color);
        jButton5.setForeground(color);
        jButton6.setForeground(color);
        jButton7.setForeground(color);

        jButtonDoiMau.setForeground(color);
        jButtonnenden.setForeground(color);
        jButtonnenTrang.setForeground(color);
    }//GEN-LAST:event_jButtonDoiMauActionPerformed

    private void jButtonnenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnenTrangActionPerformed
        jLabelnen.setVisible(false);
    }//GEN-LAST:event_jButtonnenTrangActionPerformed

    private void jButtonnendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnendenActionPerformed
        jLabelnen.setVisible(true);
    }//GEN-LAST:event_jButtonnendenActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOS = null;
        XSSFWorkbook excelJTableExporter = null;
        XSSFSheet excelSheet = null;
        JFileChooser excelChooser = new JFileChooser("D:\\FileExcel");
        excelChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelChooser.setFileFilter(fnef);
        int EXChoosee = excelChooser.showSaveDialog(null);
        if (EXChoosee == JFileChooser.APPROVE_OPTION) {

            try {
                excelJTableExporter = new XSSFWorkbook();
                excelSheet = excelJTableExporter.createSheet("JTable Sheet");

                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        XSSFCell excelCell = excelRow.createCell(j);

                        excelCell.setCellValue(jTable1.getValueAt(i, j).toString());

                    }
                }
                excelFOU = new FileOutputStream(excelChooser.getSelectedFile() + ".xlsx");
                excelBOS = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOS);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
            } finally {
                try {
                    if (excelBOS != null) {
                        excelBOS.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }
                    if (excelJTableExporter != null) {
                        excelJTableExporter.close();
                    }
                } catch (IOException e) {
                }
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonDoiMau;
    private javax.swing.JButton jButtonnenTrang;
    private javax.swing.JButton jButtonnenden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelnen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDocGia;
    private javax.swing.JRadioButton jRadioButtonMuonHet;
    private javax.swing.JRadioButton jRadioButtonNXB;
    private javax.swing.JRadioButton jRadioButtonSach;
    private javax.swing.JRadioButton jRadioButtonTheLoai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
