/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPannelHotrogiaodienchinh;

import Model.TraSachCode;
import static View.GiaoDienChinh.GiaoDienChinh.jPanelLamViec;
import Control.KNCSDLTraSach;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TrasahJPanel extends javax.swing.JPanel {

    private ArrayList<TraSachCode> list;
    private DefaultTableModel model;

    public TrasahJPanel() throws SQLException, ClassNotFoundException {
        initComponents();
        list = new KNCSDLTraSach().LayThongTin();
        model = (DefaultTableModel) jTableTraSach.getModel();
        for (int i = 0; i < list.size(); i++) {
            TraSachCode x = list.get(i);
            model.addRow(new Object[]{
                x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayTra(), x.getTenSinhVien(), x.getMaTheSinhVien()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        a1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        a9 = new javax.swing.JLabel();
        jButtonThem = new javax.swing.JButton();
        jButtonTaiLai = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        jTextFieldSoPhieuMuon = new javax.swing.JTextField();
        jTextFieldMaTheSinhVien = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextFieldTenSinhVien = new javax.swing.JTextField();
        jTextFieldNgayTra = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jTextFieldMaSoSach = new javax.swing.JTextField();
        jTextFieldTenSach = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        a10 = new javax.swing.JLabel();
        jRadioButtonMa = new javax.swing.JRadioButton();
        jRadioButtonSo = new javax.swing.JRadioButton();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTraSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButtonDoiMau = new javax.swing.JButton();
        jButtonnenTrang = new javax.swing.JButton();
        jButtonnenden = new javax.swing.JButton();
        jLabelnen = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1.setText("DANH MỤC TRẢ SÁCH ");
        add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 460, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a9.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        a9.setForeground(new java.awt.Color(0, 0, 0));
        a9.setText("Xử Lí ");
        jPanel7.add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonThem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonThem.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\add.png")); // NOI18N
        jButtonThem.setText("Thêm ");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        jButtonTaiLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTaiLai.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\undo.png")); // NOI18N
        jButtonTaiLai.setText("Tải Lại");
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonTaiLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, 40));

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\repair.png")); // NOI18N
        jButton10.setText("Sửa");
        jButton10.setActionCommand("Sửa ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\delete.png")); // NOI18N
        jButton11.setText("Xóa");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 40));

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\in.png")); // NOI18N
        jButton12.setText("In");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, 40));

        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\exit.png")); // NOI18N
        jButton13.setText("Thoát");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 100, 40));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Tìm Kiếm Thông Tin");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 170, -1));

        jRadioButton3.setText("Tìm Theo Mã Thẻ Sinh Viên");
        jPanel8.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jRadioButton4.setText("Tìm Theo Số Phiếu Mượn");
        jRadioButton4.setToolTipText("");
        jPanel8.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 30));

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("Tìm Kiếm ");
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 450, 100));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 450, 90));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 370, 170));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Thông Tin Trả Sách");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 200, -1));

        a3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("Tên Sách ");
        jPanel4.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        a6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a6.setForeground(new java.awt.Color(0, 0, 0));
        a6.setText("Ngày Trả ");
        jPanel4.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        a5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a5.setForeground(new java.awt.Color(0, 0, 0));
        a5.setText("Số Lượng");
        jPanel4.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        a2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setText("Số Phiếu Mượn");
        jPanel4.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        a8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a8.setForeground(new java.awt.Color(0, 0, 0));
        a8.setText("Mã thẻ Sinh Viên");
        jPanel4.add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        a7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a7.setForeground(new java.awt.Color(0, 0, 0));
        a7.setText("Tên Sinh Viên");
        jPanel4.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        a4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("Mã Số Sách");
        jPanel4.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextFieldSoPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldSoPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        jTextFieldMaTheSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldMaTheSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaTheSinhVienActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldMaTheSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, 30));
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 200, 30));

        jTextFieldTenSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldTenSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 200, 30));

        jTextFieldNgayTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldNgayTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 30));

        jTextFieldSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, 30));

        jTextFieldMaSoSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldMaSoSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 30));

        jTextFieldTenSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel4.add(jTextFieldTenSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, 400));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        a10.setForeground(new java.awt.Color(0, 0, 0));
        a10.setText("Tìm Kiếm Thông Tin");
        jPanel9.add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 210, -1));

        buttonGroup1.add(jRadioButtonMa);
        jRadioButtonMa.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonMa.setText("Tìm Theo Mã Thẻ Sinh Viên");
        jPanel9.add(jRadioButtonMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        buttonGroup1.add(jRadioButtonSo);
        jRadioButtonSo.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonSo.setText("Tìm Theo Số Phiếu Mượn");
        jRadioButtonSo.setToolTipText("");
        jPanel9.add(jRadioButtonSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
        jPanel9.add(jTextFieldTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 30));

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTimKiem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\timkiem.png")); // NOI18N
        jButtonTimKiem.setText("Tìm Kiếm ");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 450, 100));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 190, -1));

        jTableTraSach.setAutoCreateRowSorter(true);
        jTableTraSach.setBackground(new java.awt.Color(153, 153, 153));
        jTableTraSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTableTraSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Phiếu Mượn", "Tên Sách", "Mã Số Sách", "Số Lượng", "Ngày Trả", "Tên Sinh Viên", "Mã Thẻ Sinh Viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTraSach.setShowGrid(true);
        jTableTraSach.getTableHeader().setReorderingAllowed(false);
        jTableTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTraSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTraSach);
        if (jTableTraSach.getColumnModel().getColumnCount() > 0) {
            jTableTraSach.getColumnModel().getColumn(0).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(1).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(2).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(3).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(4).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(5).setResizable(false);
            jTableTraSach.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 800, 510));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhDanhMucTraSach\\images.jfif")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 220, 170));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 220, 170));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDoiMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDoiMau.setText("Đổi Màu");
        jButtonDoiMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiMauActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonDoiMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        jButtonnenTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenTrang.setText("Nền Trắng");
        jButtonnenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnenTrangActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 110, 30));

        jButtonnenden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenden.setText("Nền Đen");
        jButtonnenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnendenActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 30));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 90));

        jLabelnen.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\den.jpg")); // NOI18N
        add(jLabelnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Bạn chắc chắc là mình muốn xóa ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            int index = jTableTraSach.getSelectedRow();
            int SoPhieuMuon = Integer.parseInt(model.getValueAt(index, 0) + "");
            try {
                    if (new KNCSDLTraSach().Xoa(SoPhieuMuon)) {
                        JOptionPane.showMessageDialog(this, " Xóa Thành Công ");
                        model.removeRow(index);
                        TaiLai();                    }             
              } catch (Exception ex) {
                Logger.getLogger(MuonsachJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Xóa không thành công");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        MessageFormat header = new MessageFormat("Trả Sách");
        MessageFormat footer = new MessageFormat("");
        try {
            this.jTableTraSach.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to print");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        
        if(jTextFieldSoPhieuMuon.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Số Phiếu mượn không được bỏ trống ");
            return;
        }    
        try {
            Integer.parseInt(jTextFieldSoPhieuMuon.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
            return ;
        }
        
        boolean kiemtra = false ;
        for(int i = 0; i<list.size() ; i++){
            TraSachCode muonsach = list.get(i);
            if(muonsach.getSoPhieuMuon() == Integer.parseInt(jTextFieldSoPhieuMuon.getText())){
                kiemtra = true;
            }
        }
        if(kiemtra){
            JOptionPane.showMessageDialog(this,"Số phiếu mượn đã tồn tại");
            return;
        }
        
        
        if(jTextFieldTenSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sách không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSach.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sách là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaSoSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã số sách không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldMaSoSach.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
            return ;
        }    
         
        
        if(jTextFieldSoLuong.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số lượng bắt buộc là chữ số");
            return ;
        }
        
        
        if(jTextFieldNgayTra.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ngày mượn không được để trống");
            return;
        }
        String ngaymuon = "[0-9]{2}/[0-9]{2}/[0-9]{4}" ;
        if(!jTextFieldNgayTra.getText().matches(ngaymuon)){
            JOptionPane.showMessageDialog(this,"Ngày trả bạn nhập không đúng cú pháp");
            return;
        }
        
        
        if(jTextFieldTenSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaTheSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã Thẻ sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldMaTheSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Mã thẻ sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        TraSachCode x = new TraSachCode();
        x.setSoPhieuMuon(Integer.parseInt(jTextFieldSoPhieuMuon.getText()));
        x.setTenSach(jTextFieldTenSach.getText());
        x.setMaSoSach(Integer.parseInt(jTextFieldMaSoSach.getText()));
        x.setSoLuong(Integer.parseInt(jTextFieldSoLuong.getText()));
        x.setNgayTra(jTextFieldNgayTra.getText());
        x.setTenSinhVien(jTextFieldTenSinhVien.getText());
        x.setMaTheSinhVien(jTextFieldMaTheSinhVien.getText());
        try {
            if (new KNCSDLTraSach().Them(x)) {
                JOptionPane.showMessageDialog(this, "Thêm Thành Công ");
                model.addRow(new Object[]{
                    x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayTra(), x.getTenSinhVien(), x.getMaTheSinhVien()
                });
                TaiLai();
            }
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonThemActionPerformed
    void TaiLai() throws SQLException, ClassNotFoundException {
        jButtonThem.setEnabled(false);
        jTextFieldSoPhieuMuon.setText("");
        jTextFieldTenSach.setText("");
        jTextFieldMaSoSach.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldNgayTra.setText("");
        jTextFieldTenSinhVien.setText("");
        jTextFieldMaTheSinhVien.setText("");
        jTableTraSach.clearSelection();

        try {
            list.clear();
            list = new KNCSDLTraSach().LayThongTin();

        } catch (SQLException ex) {
            Logger.getLogger(MuonsachJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        }
        for (int i = 0; i < list.size(); i++) {
            TraSachCode x = list.get(i);
            //   MuonSachCode x = list.get(i);
            model.addRow(new Object[]{
                x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayTra(), x.getTenSinhVien(), x.getMaTheSinhVien()
            });
        }
    }

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        try {
            TaiLai();
            jButtonThem.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TrasahJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTaiLaiActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

//          if(jTextFieldTenSach.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Tên sách không được bỏ trống");
//            return;
//        }
//        try {
//            jTextFieldTenSach.getText();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Tên sách là chữ và có thể kèm theo số");
//            return;
//        }
//        
//        if(jTextFieldMaSoSach.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Mã số sách không được bỏ trống");
//            return;
//        }
//        try {
//            Integer.parseInt(jTextFieldMaSoSach.getText());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this,"Số phiếu mượn bắt buộc là chữ số");
//            return ;
//        }    
//         
//        
//        if(jTextFieldSoLuong.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
//            return;
//        }
//        try {
//            Integer.parseInt(jTextFieldSoLuong.getText());
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this,"Số lượng bắt buộc là chữ số");
//            return ;
//        }
//        
//        String ngaymuon = "[0-9]{2}/[0-9]{2}/[0-9]{4}" ;
//        if(!jTextFieldNgayTra.getText().matches(ngaymuon)){
//            JOptionPane.showMessageDialog(this,"Ngày trả bạn nhập không đúng cú pháp!!");
//            return;
//        }
//        if(jTextFieldNgayTra.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Ngày trả không được để trống");
//            return;
//        }
//        
//        if(jTextFieldTenSinhVien.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Tên sinh viên không được bỏ trống");
//            return;
//        }
//        try {
//            jTextFieldTenSinhVien.getText();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Tên sinh viên là chữ và có thể kèm theo số");
//            return;
//        }
//        
//        if(jTextFieldMaTheSinhVien.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Mã Thẻ sinh viên không được bỏ trống");
//            return;
//        }
//        try {
//            jTextFieldMaTheSinhVien.getText();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, " Mã thẻ sinh viên là chữ và có thể kèm theo số");
//            return;
//        }
         if(jTextFieldTenSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sách không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSach.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sách là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaSoSach.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã số sách không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldMaSoSach.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Mã số sách bắt buộc là chữ số");
            return ;
        }    
         
        
        if(jTextFieldSoLuong.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số lượng không được bỏ trống");
            return;
        }
        try {
            Integer.parseInt(jTextFieldSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Số lượng bắt buộc là chữ số");
            return ;
        }
        
        String ngaymuon = "[0-9]{2}/[0-9]{2}/[0-9]{4}" ;
        if(!jTextFieldNgayTra.getText().matches(ngaymuon)){
            JOptionPane.showMessageDialog(this,"Ngày trả bạn nhập không đúng cú pháp!!");
            return;
        }
        if(jTextFieldNgayTra.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ngày trả không được để trống");
            return;
        }
        
        if(jTextFieldTenSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldTenSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tên sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        if(jTextFieldMaTheSinhVien.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Mã Thẻ sinh viên không được bỏ trống");
            return;
        }
        try {
            jTextFieldMaTheSinhVien.getText();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Mã thẻ sinh viên là chữ và có thể kèm theo số");
            return;
        }
        
        
        int index = jTableTraSach.getSelectedRow();
        TraSachCode x = new TraSachCode();
        x.setSoPhieuMuon(Integer.parseInt(jTextFieldSoPhieuMuon.getText()));
        x.setTenSach(jTextFieldTenSach.getText());
        x.setMaSoSach(Integer.parseInt(jTextFieldMaSoSach.getText()));
        x.setSoLuong(Integer.parseInt(jTextFieldSoLuong.getText()));
        x.setNgayTra(jTextFieldNgayTra.getText());
        x.setTenSinhVien(jTextFieldTenSinhVien.getText());
        x.setMaTheSinhVien(jTextFieldMaTheSinhVien.getText());
        try {
            if (new KNCSDLTraSach().Sua(x)) {
                JOptionPane.showMessageDialog(this, "Sửa Thành Công ");

                model.setValueAt(x.getSoPhieuMuon(), index, 0);
                model.setValueAt(x.getTenSach(), index, 1);
                model.setValueAt(x.getMaSoSach(), index, 2);
                model.setValueAt(x.getSoLuong(), index, 3);
                model.setValueAt(x.getNgayTra(), index, 4);
                model.setValueAt(x.getTenSinhVien(), index, 5);
                model.setValueAt(x.getMaTheSinhVien(), index, 6);
                TaiLai();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }      
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
       int ret = JOptionPane.showConfirmDialog(this, "Có phải bạn muốn tìm kiếm thông tin ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
        String ma = "";
        if (jRadioButtonMa.isSelected()) {
            ma = "MaTheSinhVien";
        }
        if (jRadioButtonSo.isSelected()) {
            ma = "SoPhieuMuon";
        }
        String tim = jTextFieldTimKiem.getText();
        try {
            list.clear();
            list = new KNCSDLTraSach().TimKiemThongTin(ma, tim);
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            for (int i = 0; i < list.size(); i++) {
                TraSachCode x = list.get(i);
                JOptionPane.showMessageDialog(this , "Tìm kiếm thông tin thành công ");
                model.addRow(new Object[]{
                    x.getSoPhieuMuon(), x.getTenSach(), x.getMaSoSach(), x.getSoLuong(), x.getNgayTra(), x.getTenSinhVien(), x.getMaTheSinhVien()
                });
            }
        } catch (Exception ex) {
        }
        }else{
            JOptionPane.showMessageDialog(this,"Tìm kiếm thông tin không thành công ");
        }
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jTableTraSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTraSachMouseClicked
        jButtonThem.setEnabled(false);
        int index = jTableTraSach.getSelectedRow();
        jTextFieldSoPhieuMuon.setText(model.getValueAt(index, 0) + "");
        jTextFieldTenSach.setText(model.getValueAt(index, 1) + "");
        jTextFieldMaSoSach.setText(model.getValueAt(index, 2) + "");
        jTextFieldSoLuong.setText(model.getValueAt(index, 3) + "");
        jTextFieldNgayTra.setText(model.getValueAt(index, 4) + "");
        jTextFieldTenSinhVien.setText(model.getValueAt(index, 5) + "");
        jTextFieldMaTheSinhVien.setText(model.getValueAt(index, 6) + "");
    }//GEN-LAST:event_jTableTraSachMouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        GiaoDienChinhJPanel x = new GiaoDienChinhJPanel();
        x.setBounds(0, 0, 1200, 749);
        jPanelLamViec.removeAll();
        jPanelLamViec.add(x);
        jPanelLamViec.validate();
        jPanelLamViec.repaint();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextFieldMaTheSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaTheSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaTheSinhVienActionPerformed

    private void jButtonDoiMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiMauActionPerformed
        Color color = JColorChooser.showDialog(this, "Chọn màu", Color.yellow);
        
        jTableTraSach.setForeground(color);
        a1.setForeground(color);
        a2.setForeground(color);
        a3.setForeground(color);
        a4.setForeground(color);
        a5.setForeground(color);
        a6.setForeground(color);
        a7.setForeground(color);
        a8.setForeground(color);
        a9.setForeground(color);
        a10.setForeground(color);
        

        a6.setForeground(color);
        jRadioButtonMa.setForeground(color);
        jRadioButtonSo.setForeground(color);
        //        jRadioButtonMa.setForeground(color);
        //        jRadioButtonTen.setForeground(color);
        jButton12.setForeground(color);
        jButton10.setForeground(color);
        jButtonThem.setForeground(color);
        jButtonTaiLai.setForeground(color);
        jButtonTimKiem.setForeground(color);
        jButton11.setForeground(color);
        jButton13.setForeground(color);
        jButtonDoiMau.setForeground(color);
        jButtonnenden.setForeground(color);
        jButtonnenTrang.setForeground(color);
    }//GEN-LAST:event_jButtonDoiMauActionPerformed

    private void jButtonnenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnenTrangActionPerformed
        jLabelnen.setVisible(false);
    }//GEN-LAST:event_jButtonnenTrangActionPerformed

    private void jButtonnendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnendenActionPerformed
        jLabelnen.setVisible(true);
    }//GEN-LAST:event_jButtonnendenActionPerformed
//void TaiLai(){
//    
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButtonDoiMau;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonnenTrang;
    private javax.swing.JButton jButtonnenden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelnen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButtonMa;
    private javax.swing.JRadioButton jRadioButtonSo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTraSach;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldMaSoSach;
    private javax.swing.JTextField jTextFieldMaTheSinhVien;
    private javax.swing.JTextField jTextFieldNgayTra;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldSoPhieuMuon;
    private javax.swing.JTextField jTextFieldTenSach;
    private javax.swing.JTextField jTextFieldTenSinhVien;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables

    private Object KetNoiCSDLTraSach() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
