/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPannelHotrogiaodienchinh;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author ASUS
 */
public class TroGiupJpanel extends javax.swing.JPanel {

    /**
     * Creates new form TroGiupJpanel
     */
    public TroGiupJpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButtonDoiMau = new javax.swing.JButton();
        jButtonnenTrang = new javax.swing.JButton();
        jButtonnenden = new javax.swing.JButton();
        jLabelnen = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhanhThamKhao\\duy.jpg")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 590));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 570, 590));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đề Tài  :  Xây dựng ứng dụng quản lí Thư Viện");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 450, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mọi thông tin chi tiết xin liên hệ tác giả ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 680, 450, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên : Nguyễn Lê Hữu Duy");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lớp :  20IT7");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MSSV  :  20IT309");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Môn Học  :  Java nâng cao");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 290, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Thông Tin Tác Giả : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 310, -1));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDoiMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDoiMau.setText("Đổi Màu");
        jButtonDoiMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoiMauActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonDoiMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jButtonnenTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenTrang.setText("Nền Trắng");
        jButtonnenTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnenTrangActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 110, 30));

        jButtonnenden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonnenden.setText("Nền Đen");
        jButtonnenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnendenActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonnenden, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 370, 70));

        jLabelnen.setIcon(new javax.swing.ImageIcon("D:\\ApacheNetBean\\NetBeansProjects\\QuanLiThuVienHocKy2\\src\\HinhAnhMuonSach\\den.jpg")); // NOI18N
        jPanel1.add(jLabelnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDoiMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoiMauActionPerformed
        Color color = JColorChooser.showDialog(this, "Chọn màu", Color.yellow);

       

        jLabel1.setForeground(color);
        jLabel4.setForeground(color);
        jLabel5.setForeground(color);
        jLabel6.setForeground(color);
        jLabel7.setForeground(color);
        jLabel8.setForeground(color);
        

        //        jRadioButtonMa.setForeground(color);
        //        jRadioButtonTen.setForeground(color);
        

        jButtonDoiMau.setForeground(color);
        jButtonnenden.setForeground(color);
        jButtonnenTrang.setForeground(color);
    }//GEN-LAST:event_jButtonDoiMauActionPerformed

    private void jButtonnenTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnenTrangActionPerformed
        jLabelnen.setVisible(false);
    }//GEN-LAST:event_jButtonnenTrangActionPerformed

    private void jButtonnendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnendenActionPerformed
        jLabelnen.setVisible(true);
    }//GEN-LAST:event_jButtonnendenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDoiMau;
    private javax.swing.JButton jButtonnenTrang;
    private javax.swing.JButton jButtonnenden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelnen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
